#!/bin/bash
set -e
DN="$1"

[ "$DN" == "" ] && echo "need NAME" && exit 1
[ -d "$DN" ] && echo "$DN exists" && exit 1

#./update_all

git clone \
	-o asf	\
	--reference `pwd`/master \
	https://git-wip-us.apache.org/repos/asf/hive.git $DN

cd $DN

git remote add kgyrtkirk git@github.com:kgyrtkirk/hive
git fetch --all
git config --local extra.ideProjects ql,common
git checkout -b $DN
git push kgyrtkirk -u HEAD

cd ..

./activate $DN
