#!/bin/bash -e

LOGMEIN_CFG="$HOME/.logmein"
HOST="$1"

function usage() {
cat << EOF
usage: $1 <host>

ensures that your default key is installed on the target system

reads the file $LOGMEIN_CFG as a dsl source:
available commands:
	pwd_auth	<password>
	ssh_key		<path_to_key>
EOF
}

[ "$1" == "" ] && usage "$@" && exit 0


[ ! -f $LOGMEIN_CFG ] && echo "error: no $LOGMEIN_CFG" && exit 1


if ssh -o PasswordAuthentication=no "$1"; then
	echo ok
	exit 0
fi

MY_KEY="`cat ~/.ssh/id_rsa.pub`"
[ "$MY_KEY" == "" ] && echo "default ssh key not found" && exit 1
deployCmd="mkdir .ssh;grep -qxF '$MY_KEY' .ssh/authorized_keys || echo '$MY_KEY' >> .ssh/authorized_keys"

function pwd_auth() {
	echo "trying pwd: $1"
	if sshpass -p "$1" ssh "$HOST" echo ok;then
		echo "install"
		sshpass -p "$1" ssh "$HOST" "mkdir .ssh;grep -qxF '$MY_KEY' .ssh/authorized_keys || echo '$MY_KEY' >> .ssh/authorized_keys"
		banner "ok"
		exit 0
	fi
}


# execute dsl
. $LOGMEIN_CFG

banner fail
exit 1
